leftnav:
- identifier: 5d5f4502-4533-4899-89ea-96fc661bdf70
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 19f281ea-6341-90ac-2c77-06cf85b48714
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: a1704e82-97c3-a5e2-894d-fee93ed68e10
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: b07be87f-560b-f351-fb8d-8a661713fe93
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 83f38119-a72f-810c-28ff-034f3b212f3a
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
